version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: dogan
      MYSQL_PASSWORD: dogandevops_1
    networks:
      - dogannet

  myapp:
    image: dogan2010/bookstoreapi:latest # you have to enter your own Dockerhub address
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - dogannet

networks:
  dogannet: